SELECT
    BIN.ID AS bin_id,
    BIN.BINNUMBER AS bin_number,
    BIN.LOCATION AS location_id,
    LOCATION.NAME AS location_name,
    ITEM.ITEMID AS item_name,
    INVENTORYNUMBER.INVENTORYNUMBER AS serial_or_lot_number,
    SUM(INVENTORYBALANCE.QUANTITYONHAND) AS quantity_on_hand
FROM
    InventoryBalance INVENTORYBALANCE
    INNER JOIN Bin BIN
        ON INVENTORYBALANCE.BINNUMBER = BIN.ID
    INNER JOIN Location LOCATION
        ON BIN.LOCATION = LOCATION.ID
    INNER JOIN Item ITEM
        ON INVENTORYBALANCE.ITEM = ITEM.ID
    LEFT JOIN InventoryNumber INVENTORYNUMBER
        ON INVENTORYBALANCE.INVENTORYNUMBER = INVENTORYNUMBER.ID
WHERE
    BIN.LOCATION = 3
    AND INVENTORYBALANCE.QUANTITYONHAND > 0
GROUP BY
    BIN.ID,
    BIN.BINNUMBER,
    BIN.LOCATION,
    LOCATION.NAME,
    ITEM.ITEMID,
    INVENTORYNUMBER.INVENTORYNUMBER
ORDER BY
    BIN.BINNUMBER,
    ITEM.ITEMID,
    INVENTORYNUMBER.INVENTORYNUMBER